---
name: CI

on:
  push:
    branches:
      - main


jobs:
  function-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'func-dojo-cicd-skool'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: func-dojo-cicd-skool/package-lock.json
      - name: Install node dependencies
        run: |
          npm install
          npm install @azure/functions
      - name: Run npm test
        run: |
          npm test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: reports/
  code-quality:
    runs-on: ubuntu-latest
    needs: function-tests
    defaults:
      run:
        working-directory: 'func-dojo-cicd-skool'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: func-dojo-cicd-skool/package-lock.json
      - name: Install node dependencies
        working-directory: 'func-dojo-cicd-skool'
        run: |
          npm install
      - name : linter
        working-directory: 'func-dojo-cicd-skool'
        run : npm run lint
      - name: audit dependencies
        working-directory: 'func-dojo-cicd-skool'
        continue-on-error: true
        run: npm run audit-dependencies
      - name: sonar
        working-directory: 'func-dojo-cicd-skool'
        continue-on-error: true
        run : |
          npm run start-local-sonarqube
          npm run sonar
          npm run stop-local-sonarqube
  package-build:
    runs-on: ubuntu-latest
    needs: code-quality
    defaults:
      run:
        working-directory: 'func-dojo-cicd-skool'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: func-dojo-cicd-skool/package-lock.json
      - name: Install node dependencies
        working-directory: 'func-dojo-cicd-skool'
        run: |
          npm install
      - name: package-wheel
        working-directory: 'func-dojo-cicd-skool'
        run: npm run build
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: package-wheel
          path: func-dojo-cicd-skool/dist


